// This file exports model factory functions for all entities
const { DataTypes } = require("sequelize");

const createModel = (tableName, fields) => (sequelize) => {
  return sequelize.define(tableName, {
    id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
    ...fields,
    created_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
    updated_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  }, { tableName, timestamps: false });
};

// Export all model factories
module.exports = {
  Role: createModel('roles', { name: DataTypes.STRING, description: DataTypes.TEXT, permissions: DataTypes.JSON }),
  PledgeAuditLog: createModel('pledge_audit_logs', { pledge_id: DataTypes.UUID, user_id: DataTypes.UUID, action: DataTypes.STRING, details: DataTypes.JSON }),
  PledgePayment: createModel('pledge_payments', { pledge_id: DataTypes.UUID, user_id: DataTypes.UUID, amount: DataTypes.DECIMAL(10,2), status: DataTypes.STRING }),
  AdvisorPledgeAccessRequest: createModel('advisor_pledge_access_requests', { advisor_id: DataTypes.UUID, user_id: DataTypes.UUID, status: DataTypes.STRING }),
  FundAllocation: createModel('fund_allocations', { fund_id: DataTypes.UUID, stock_symbol: DataTypes.STRING, percentage: DataTypes.DECIMAL(5,2) }),
  FundPlan: createModel('fund_plans', { name: DataTypes.STRING, description: DataTypes.TEXT, target_return: DataTypes.DECIMAL(5,2) }),
  FundWallet: createModel('fund_wallets', { user_id: DataTypes.UUID, balance: DataTypes.DECIMAL(15,2), currency: DataTypes.STRING }),
  FundNotification: createModel('fund_notifications', { user_id: DataTypes.UUID, fund_id: DataTypes.UUID, message: DataTypes.TEXT }),
  FundWithdrawalRequest: createModel('fund_withdrawal_requests', { user_id: DataTypes.UUID, amount: DataTypes.DECIMAL(15,2), status: DataTypes.STRING }),
  FundPayoutRequest: createModel('fund_payout_requests', { user_id: DataTypes.UUID, amount: DataTypes.DECIMAL(15,2), status: DataTypes.STRING }),
  FundInvoice: createModel('fund_invoices', { user_id: DataTypes.UUID, amount: DataTypes.DECIMAL(15,2), status: DataTypes.STRING }),
  TrustScoreLog: createModel('trust_score_logs', { user_id: DataTypes.UUID, score: DataTypes.INTEGER, reason: DataTypes.TEXT }),
  Advisor: createModel('advisors', { user_id: DataTypes.UUID, name: DataTypes.STRING, avatar_url: DataTypes.STRING, bio: DataTypes.TEXT, rating: DataTypes.DECIMAL(3,2) }),
  UserInvestment: createModel('user_investments', { user_id: DataTypes.UUID, stock_symbol: DataTypes.STRING, quantity: DataTypes.DECIMAL(15,4), avg_price: DataTypes.DECIMAL(15,4) }),
  Investor: createModel('investors', { user_id: DataTypes.UUID, name: DataTypes.STRING, type: DataTypes.STRING, status: DataTypes.STRING }),
  InvestmentRequest: createModel('investment_requests', { user_id: DataTypes.UUID, amount: DataTypes.DECIMAL(15,2), status: DataTypes.STRING }),
  InvestorRequest: createModel('investor_requests', { user_id: DataTypes.UUID, investor_type: DataTypes.STRING, status: DataTypes.STRING }),
  Event: createModel('events', { title: DataTypes.STRING, description: DataTypes.TEXT, start_date: DataTypes.DATE, end_date: DataTypes.DATE, location: DataTypes.STRING, status: DataTypes.STRING, organizer_id: DataTypes.UUID }),
  EventTicket: createModel('event_tickets', { event_id: DataTypes.UUID, user_id: DataTypes.UUID, ticket_type: DataTypes.STRING, price: DataTypes.DECIMAL(10,2), status: DataTypes.STRING }),
  EventAttendee: createModel('event_attendees', { event_id: DataTypes.UUID, user_id: DataTypes.UUID, status: DataTypes.STRING, checked_in: DataTypes.BOOLEAN }),
  EventReview: createModel('event_reviews', { event_id: DataTypes.UUID, user_id: DataTypes.UUID, rating: DataTypes.INTEGER, comment: DataTypes.TEXT }),
  EventCommissionTracking: createModel('event_commission_tracking', { event_id: DataTypes.UUID, amount: DataTypes.DECIMAL(10,2), status: DataTypes.STRING }),
  RefundRequest: createModel('refund_requests', { ticket_id: DataTypes.UUID, user_id: DataTypes.UUID, reason: DataTypes.TEXT, status: DataTypes.STRING }),
  EventCheckIn: createModel('event_check_ins', { event_id: DataTypes.UUID, attendee_id: DataTypes.UUID, checked_in_at: DataTypes.DATE }),
  EventPromoCode: createModel('event_promo_codes', { event_id: DataTypes.UUID, code: DataTypes.STRING, discount_percent: DataTypes.INTEGER, max_uses: DataTypes.INTEGER }),
  EventReminder: createModel('event_reminders', { event_id: DataTypes.UUID, user_id: DataTypes.UUID, remind_at: DataTypes.DATE }),
  EventFeedback: createModel('event_feedback', { event_id: DataTypes.UUID, user_id: DataTypes.UUID, feedback: DataTypes.TEXT, rating: DataTypes.INTEGER }),
  EventOrganizer: createModel('event_organizers', { user_id: DataTypes.UUID, name: DataTypes.STRING, status: DataTypes.STRING }),
  FinInfluencer: createModel('finfluencers', { user_id: DataTypes.UUID, name: DataTypes.STRING, avatar_url: DataTypes.STRING, bio: DataTypes.TEXT, follower_count: DataTypes.INTEGER, status: DataTypes.STRING, is_featured: DataTypes.BOOLEAN }),
  Course: createModel('courses', { title: DataTypes.STRING, description: DataTypes.TEXT, instructor_id: DataTypes.UUID, price: DataTypes.DECIMAL(10,2), status: DataTypes.STRING, category: DataTypes.STRING, is_featured: DataTypes.BOOLEAN, enrollment_count: DataTypes.INTEGER }),
  CourseEnrollment: createModel('course_enrollments', { course_id: DataTypes.UUID, user_id: DataTypes.UUID, status: DataTypes.STRING, progress: DataTypes.INTEGER, enrolled_at: DataTypes.DATE }),
  InfluencerPost: createModel('influencer_posts', { influencer_id: DataTypes.UUID, content: DataTypes.TEXT, media_urls: DataTypes.JSON, status: DataTypes.STRING }),
  RevenueTransaction: createModel('revenue_transactions', { user_id: DataTypes.UUID, amount: DataTypes.DECIMAL(15,2), type: DataTypes.STRING, status: DataTypes.STRING }),
  PayoutRequest: createModel('payout_requests', { user_id: DataTypes.UUID, amount: DataTypes.DECIMAL(15,2), payment_method: DataTypes.STRING, payment_details: DataTypes.JSON, status: DataTypes.STRING }),
  ModerationLog: createModel('moderation_logs', { moderator_id: DataTypes.UUID, action: DataTypes.STRING, target_type: DataTypes.STRING, target_id: DataTypes.UUID, reason: DataTypes.TEXT }),
  ContactInquiry: createModel('contact_inquiries', { name: DataTypes.STRING, email: DataTypes.STRING, subject: DataTypes.STRING, message: DataTypes.TEXT, status: DataTypes.STRING }),
  Feedback: createModel('feedback', { user_id: DataTypes.UUID, type: DataTypes.STRING, content: DataTypes.TEXT, status: DataTypes.STRING }),
  PromoCode: createModel('promo_codes', { code: DataTypes.STRING, discount_percent: DataTypes.INTEGER, max_uses: DataTypes.INTEGER, uses_count: DataTypes.INTEGER, expires_at: DataTypes.DATE, is_active: DataTypes.BOOLEAN }),
  SubscriptionTransaction: createModel('subscription_transactions', { subscription_id: DataTypes.UUID, amount: DataTypes.DECIMAL(10,2), status: DataTypes.STRING }),
  Subscription: createModel('subscriptions', { user_id: DataTypes.UUID, plan_id: DataTypes.UUID, status: DataTypes.STRING, finfluencer_id: DataTypes.UUID, type: DataTypes.STRING }),
  SubscriptionPlan: createModel('subscription_plans', { name: DataTypes.STRING, price: DataTypes.DECIMAL(10,2), interval: DataTypes.STRING, features: DataTypes.JSON }),
  Poll: createModel('polls', { chat_room_id: DataTypes.UUID, question: DataTypes.STRING, options: DataTypes.JSON, votes: DataTypes.JSON, total_votes: DataTypes.INTEGER, status: DataTypes.STRING, expires_at: DataTypes.DATE }),
  PollVote: createModel('poll_votes', { poll_id: DataTypes.UUID, user_id: DataTypes.UUID, option_index: DataTypes.INTEGER }),
  Referral: createModel('referrals', { referrer_id: DataTypes.UUID, referred_id: DataTypes.UUID, code: DataTypes.STRING, status: DataTypes.STRING, reward_amount: DataTypes.DECIMAL(10,2) }),
  ReferralBadge: createModel('referral_badges', { name: DataTypes.STRING, description: DataTypes.TEXT, required_referrals: DataTypes.INTEGER, image_url: DataTypes.STRING }),
  Message: createModel('messages', { chat_room_id: DataTypes.UUID, user_id: DataTypes.UUID, content: DataTypes.TEXT, is_pinned: DataTypes.BOOLEAN, reply_to_id: DataTypes.UUID }),
  MessageReaction: createModel('message_reactions', { message_id: DataTypes.UUID, user_id: DataTypes.UUID, emoji: DataTypes.STRING }),
  ChatRoom: createModel('chat_rooms', { name: DataTypes.STRING, description: DataTypes.TEXT, stock_symbol: DataTypes.STRING, is_public: DataTypes.BOOLEAN, status: DataTypes.STRING, participant_count: DataTypes.INTEGER, owner_id: DataTypes.UUID }),
  ChatRoomParticipant: createModel('chat_room_participants', { chat_room_id: DataTypes.UUID, user_id: DataTypes.UUID, role: DataTypes.STRING, joined_at: DataTypes.DATE }),
  Meeting: createModel('meetings', { chat_room_id: DataTypes.UUID, stock_symbol: DataTypes.STRING, meeting_url: DataTypes.STRING, status: DataTypes.STRING, start_time: DataTypes.DATE, end_time: DataTypes.DATE, participant_count: DataTypes.INTEGER, max_participants: DataTypes.INTEGER }),
  TypingIndicator: createModel('typing_indicators', { chat_room_id: DataTypes.UUID, user_id: DataTypes.UUID, is_typing: DataTypes.BOOLEAN }),
  News: createModel('news', { title: DataTypes.STRING, content: DataTypes.TEXT, category: DataTypes.STRING, stock_symbols: DataTypes.STRING, tags: DataTypes.STRING, status: DataTypes.STRING, published_at: DataTypes.DATE }),
  Notification: createModel('notifications', { user_id: DataTypes.UUID, type: DataTypes.STRING, title: DataTypes.STRING, message: DataTypes.TEXT, is_read: DataTypes.BOOLEAN, data: DataTypes.JSON }),
  NotificationSetting: createModel('notification_settings', { user_id: DataTypes.UUID, email_enabled: DataTypes.BOOLEAN, push_enabled: DataTypes.BOOLEAN, sms_enabled: DataTypes.BOOLEAN }),
  PlatformSetting: createModel('platform_settings', { key: DataTypes.STRING, value: DataTypes.TEXT, updated_by: DataTypes.UUID }),
  EntityConfig: createModel('entity_configs', { entity_type: DataTypes.STRING, config: DataTypes.JSON, updated_by: DataTypes.UUID }),
  AuditLog: createModel('audit_logs', { user_id: DataTypes.UUID, action: DataTypes.STRING, entity_type: DataTypes.STRING, entity_id: DataTypes.UUID, old_data: DataTypes.JSON, new_data: DataTypes.JSON, description: DataTypes.TEXT, ip_address: DataTypes.STRING, user_agent: DataTypes.STRING }),
  ModuleApprovalRequest: createModel('module_approval_requests', { module_name: DataTypes.STRING, requested_by: DataTypes.UUID, status: DataTypes.STRING, approved_by: DataTypes.UUID, approved_at: DataTypes.DATE, rejection_reason: DataTypes.TEXT }),
  Review: createModel('reviews', { user_id: DataTypes.UUID, entity_type: DataTypes.STRING, entity_id: DataTypes.UUID, rating: DataTypes.INTEGER, title: DataTypes.STRING, content: DataTypes.TEXT, status: DataTypes.STRING }),
  AdvisorRecommendation: createModel('advisor_recommendations', { advisor_id: DataTypes.UUID, stock_symbol: DataTypes.STRING, action: DataTypes.STRING, target_price: DataTypes.DECIMAL(15,4), reason: DataTypes.TEXT, status: DataTypes.STRING }),
  AdvisorPledgeCommission: createModel('advisor_pledge_commissions', { advisor_id: DataTypes.UUID, pledge_id: DataTypes.UUID, amount: DataTypes.DECIMAL(10,2), status: DataTypes.STRING }),
  AdCampaign: createModel('ad_campaigns', { advertiser_id: DataTypes.UUID, name: DataTypes.STRING, budget: DataTypes.DECIMAL(15,2), status: DataTypes.STRING, start_date: DataTypes.DATE, end_date: DataTypes.DATE, priority: DataTypes.INTEGER }),
  AdTransaction: createModel('ad_transactions', { campaign_id: DataTypes.UUID, amount: DataTypes.DECIMAL(10,2), type: DataTypes.STRING }),
  CampaignBilling: createModel('campaign_billing', { campaign_id: DataTypes.UUID, amount: DataTypes.DECIMAL(15,2), status: DataTypes.STRING }),
  Vendor: createModel('vendors', { name: DataTypes.STRING, category: DataTypes.STRING, status: DataTypes.STRING, contact_email: DataTypes.STRING }),
  AlertConfiguration: createModel('alert_configurations', { user_id: DataTypes.UUID, alert_type: DataTypes.STRING, conditions: DataTypes.JSON, is_active: DataTypes.BOOLEAN }),
  Watchlist: createModel('watchlists', { user_id: DataTypes.UUID, name: DataTypes.STRING, stocks: DataTypes.JSON }),
  Portfolio: createModel('portfolios', { user_id: DataTypes.UUID, name: DataTypes.STRING, description: DataTypes.TEXT }),
  PortfolioHolding: createModel('portfolio_holdings', { portfolio_id: DataTypes.UUID, stock_symbol: DataTypes.STRING, quantity: DataTypes.DECIMAL(15,4), cost_basis: DataTypes.DECIMAL(15,2), current_value: DataTypes.DECIMAL(15,2) }),
  ChatBot: createModel('chat_bots', { name: DataTypes.STRING, type: DataTypes.STRING, description: DataTypes.TEXT, status: DataTypes.STRING, config: DataTypes.JSON }),
  BotConversation: createModel('bot_conversations', { bot_id: DataTypes.UUID, user_id: DataTypes.UUID, role: DataTypes.STRING, message: DataTypes.TEXT }),
  Report: createModel('reports', { user_id: DataTypes.UUID, type: DataTypes.STRING, params: DataTypes.JSON, status: DataTypes.STRING, result_url: DataTypes.STRING, completed_at: DataTypes.DATE }),
  AnalyticsEvent: createModel('analytics_events', { event_type: DataTypes.STRING, event_data: DataTypes.JSON, user_id: DataTypes.UUID, session_id: DataTypes.STRING }),
};